// RobotBuilder Version: 3.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotContainer.h"
#include <frc2/command/ParallelRaceGroup.h>
#include <frc/smartdashboard/SmartDashboard.h>



RobotContainer::RobotContainer() : m_autonomousCommand(
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
&m_subsystem1){

      


    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("Command 5", new Command5());
    frc::SmartDashboard::PutData("Command 4", new Command4());
    frc::SmartDashboard::PutData("Command 3: one", new Command3(1, &m_subsystem2));
    frc::SmartDashboard::PutData("Command 3: two", new Command3(2, &m_subsystem2));
    frc::SmartDashboard::PutData("Command 2", new Command2( &m_subsystem2 ));
    frc::SmartDashboard::PutData("Command 1", new Command1( &m_subsystem1 ));
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand( &m_subsystem1 ));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OI-CONSTRUCTOR
      


    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("Command 5", new Command5());
    frc::SmartDashboard::PutData("Command 4", new Command4());
    frc::SmartDashboard::PutData("Command 3: one", new Command3(1, &m_subsystem2));
    frc::SmartDashboard::PutData("Command 3: two", new Command3(2, &m_subsystem2));
    frc::SmartDashboard::PutData("Command 2", new Command2( &m_subsystem2 ));
    frc::SmartDashboard::PutData("Command 1", new Command1( &m_subsystem1 ));
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand( &m_subsystem1 ));


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OI-CONSTRUCTOR

    ConfigureButtonBindings();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT-COMMANDS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT-COMMANDS

}

void RobotContainer::ConfigureButtonBindings() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS

frc2::JoystickButton m_joystickButton1{&m_joystick1, 1};
frc2::JoystickButton m_joystickButton2{&m_joystick1, 2};
frc2::JoystickButton m_joystickButton3{&m_joystick1, 3};
frc2::JoystickButton m_joystickButton4{&m_joystick1, 4};

m_joystickButton1.WhenPressed(Command1( &m_subsystem1 ), false);
m_joystickButton2.WhenPressed(Command2( &m_subsystem2 ).WithTimeout(3.0_s), true);
m_joystickButton3.WhenPressed(Command3(1, &m_subsystem2).WithTimeout(5.0_s), false);
m_joystickButton4.WhenPressed(Command4(), true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS


frc2::Command* RobotContainer::GetAutonomousCommand() {
  // An example command will be run in autonomous
  return &m_autonomousCommand;
}
