// RobotBuilder Version: 3.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

#include "Commands/Command2.h"

Command2::Command2(Subsystem2* subsystem2)
:m_subsystem2(subsystem2){

    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(Robot::chassis.get());
    SetName("Command2");
    AddRequirements(m_subsystem2);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

}

// Called just before this Command runs the first time
void Command2::Initialize() {
    std::cout << "Command 2" << std::endl;

}

// Called repeatedly when this Command is scheduled to run
void Command2::Execute() {

}

// Make this return true when this Command no longer needs to run execute()
bool Command2::IsFinished() {
    return true;
}

// Called once after isFinished returns true
void Command2::End(bool interrupted) {

}

bool Command2::RunsWhenDisabled() const {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return true;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}
