// RobotBuilder Version: 3.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

#include "commands/Command3.h"

Command3::Command3(double param1 ,Subsystem2* subsystem2) :
    m_param1(param1)
,     m_subsystem2(subsystem2){

    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(Robot::chassis.get());
    SetName("Command3");
    AddRequirements(m_subsystem2);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

}

// Called just before this Command runs the first time
void Command3::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void Command3::Execute() {

}

// Make this return true when this Command no longer needs to run execute()
bool Command3::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void Command3::End(bool interrupted) {

}

bool Command3::RunsWhenDisabled() const {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}
