// RobotBuilder Version: 3.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Subsystems/Subsystem1.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Subsystems/Subsystem1.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
const std::string Subsystem1::const1 = "abc";
const int Subsystem1::const2 = 5;
const double Subsystem1::const3 = 6;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Subsystem1::Subsystem1(){
SetName("Subsystem1");
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
 AddChild("Speed Controller 1", &m_speedController1);
 
 AddChild("AnalogGyro 1", &m_analogGyro1);
 m_analogGyro1.SetSensitivity(0.007);
 AddChild("AnalogAccelerometer 1", &m_analogAccelerometer1);
 m_analogAccelerometer1.SetSensitivity(0.0); m_analogAccelerometer1.SetZero(2.5);
 AddChild("Quadrature Encoder 1", &m_quadratureEncoder1);
 m_quadratureEncoder1.SetDistancePerPulse(1.0);
    m_quadratureEncoder1.SetPIDSourceType(frc::PIDSourceType::kRate);
 AddChild("Indexed Encoder 1", &m_indexedEncoder1);
 m_indexedEncoder1.SetDistancePerPulse(1.0);
    m_indexedEncoder1.SetPIDSourceType(frc::PIDSourceType::kRate);
    m_indexedEncoder1.SetIndexSource((unsigned int)4, frc::Encoder::IndexingType::kResetOnRisingEdge);
 AddChild("Analog Potentiometer 1", &m_analogPotentiometer1);
 
 AddChild("Analog Input 1", &m_analogInput1);
 
 AddChild("Limit Switch 1", &m_limitSwitch1);
 
 AddChild("Digital Input 1", &m_digitalInput1);
 
 AddChild("Ultrasonic 1", &m_ultrasonic1);
 
 AddChild("PowerDistributionPanel 1", &m_powerDistributionPanel1);
 
 AddChild("Nidec Brushless 1", &m_nidecBrushless1);
 
 AddChild("Servo 1", &m_servo1);
 
 AddChild("Digital Output 1", &m_digitalOutput1);
 
 AddChild("Spike 1", &m_spike1);
 
 AddChild("Analog Output 1", &m_analogOutput1);
 
 AddChild("Compressor 1", &m_compressor1);
 
 AddChild("Solenoid 1", &m_solenoid1);
 
 AddChild("Relay Solenoid 1", &m_relaySolenoid1);
 
 AddChild("Double Solenoid 1", &m_doubleSolenoid1);
 
 AddChild("Speed Controller 4", &m_speedController4);
 
 AddChild("Speed Controller 5", &m_speedController5);
 
 AddChild("Differential Drive 1", &m_differentialDrive1);
 m_differentialDrive1.SetSafetyEnabled(true);
        m_differentialDrive1.SetExpiration(0.1);
        m_differentialDrive1.SetMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void Subsystem1::Periodic() {
    // Put code here to be run every loop

}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.
